server:
  port: 10010 # 服务端口
spring:
  application:
    name: api-gateway # 指定服务名称
# 路由规则
zuul:
  routes:
    user-server: /user-server/** #这里是映射路径
#    user-service: # 这里是路由id，随意写
#      path: /user-server/** # 这里是映射路径
#      serviceId: user-server
#      url: http://127.0.0.1:8081 # 映射路径对应的实际url地址

eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000